name: Lint+Test+Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint files
    runs-on: "ubuntu-18.04"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.8"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

  build-test:
    name: Build & Test
    runs-on: "ubuntu-18.04"
    needs: lint
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.8"
      - name: build_test
        shell: bash
        run: .github/workflows/build_and_test.sh
